version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
    - 27017:27017
    networks:
    - app-net
    command: --smallfiles
  app:
    image: joaojoseleal/analise-credito-backend
    ports:
    - 8080:8080
    networks:
    - app-net
    links:
    - mongodb
  frontend:
    image: joaojoseleal/analise-credito-frontend
    depends_on:
    - app
    ports:
    -5000:80
    networks:
    - app-net
    build:
      context: ./analisecreditofrontend